#!/usr/bin/env python
import argparse
import tiresias.server as server

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', type=int, default=3000, help="The port to listen on.")
    args = parser.parse_args()
    server.run(args.port)
