#!/usr/bin/python
import argparse
import webbrowser
import tiresias.client as client
from time import sleep

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--server_url', type=str, default="http://localhost:3000/", help="The server.")
    parser.add_argument('--storage_dir', type=str, default="/tmp/tiresias", help="The target data directory.")
    parser.add_argument('--storage_port', type=int, default=8000, help="The port to listen on.")
    parser.add_argument('--accept_all', action='store_true')
    parser.add_argument('--headless', action='store_true')
    parser.add_argument('--synthetic', action='store_true')
    args = parser.parse_args()
    if not args.headless:
        webbrowser.open('http://localhost:%s/' % args.storage_port, new=2)
    client.run(
        server_url=args.server_url, 
        storage_dir=args.storage_dir, 
        storage_port=args.storage_port, 
        accept_all=args.accept_all, 
        synthetic=args.synthetic
    )
