#!/usr/bin/python
import argparse
import tiresias.client as client
from setproctitle import setproctitle
setproctitle("tiresias")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--server', type=str, default="http://localhost:3000/", help="The server.")
    parser.add_argument('--db_port', type=int, default=8000, help="The port to listen on.")
    parser.add_argument('--db_dir', type=str, default="/tmp/tiresias", help="The target data directory.")
    args = parser.parse_args()

    client.run(server=args.server, data_dir=args.db_dir, port=args.db_port)
